source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RiotApi_Example', :exclusive => true do
  pod "RiotApi", :path => "../"
end

target 'RiotApi_Tests', :exclusive => true do
  pod "RiotApi", :path => "../"

  
end
